project:
  type: website

website:
  title: "My Data Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis
    right:
      - icon: github
        href: https://github.com/zwcrowley/data_project

output-dir: _site



