project:
  type: website

website:
  title: "My Data Project"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis
    right:
      - icon: github
        href: https://github.com/zwcrowley/data_project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    toc-depth: 2
    toc-location: left

output-dir: _site



